import 'package:flutter/widgets.dart';

class IconlyBold {
  IconlyBold._();

  static const kFontFam = 'IconlyBold';
  static const String kFontPkg = 'student_design_system';

  static const IconData activity =
      IconData(0xe800, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bag2 =
      IconData(0xe801, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bag =
      IconData(0xe802, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bookmark =
      IconData(0xe803, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData calendar =
      IconData(0xe804, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData callMissed =
      IconData(0xe805, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData callSilent =
      IconData(0xe806, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData call =
      IconData(0xe807, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData calling =
      IconData(0xe808, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData category =
      IconData(0xe809, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chart =
      IconData(0xe80a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chat =
      IconData(0xe80b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData discovery =
      IconData(0xe80c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData document =
      IconData(0xe80d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData download =
      IconData(0xe80e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filter2 =
      IconData(0xe80f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filter =
      IconData(0xe810, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData game =
      IconData(0xe811, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData graph =
      IconData(0xe812, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heart =
      IconData(0xe813, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData hide =
      IconData(0xe814, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData home =
      IconData(0xe815, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData image2 =
      IconData(0xe816, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData image =
      IconData(0xe817, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData location =
      IconData(0xe818, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lock =
      IconData(0xe819, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData login =
      IconData(0xe81a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData logout =
      IconData(0xe81b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData message =
      IconData(0xe81c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData notification =
      IconData(0xe81d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData password =
      IconData(0xe81e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData plus =
      IconData(0xe81f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData profile =
      IconData(0xe820, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scan =
      IconData(0xe821, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData send =
      IconData(0xe822, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shieldfail =
      IconData(0xe823, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData show =
      IconData(0xe824, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData star =
      IconData(0xe825, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData swap =
      IconData(0xe826, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData ticketStar =
      IconData(0xe827, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData ticket =
      IconData(0xe828, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData unlock =
      IconData(0xe829, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData upload =
      IconData(0xe82a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData video =
      IconData(0xe82b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wallet =
      IconData(0xe82c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData work =
      IconData(0xe82d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData user2 =
      IconData(0xe82e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData user3 =
      IconData(0xe82f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData addUser =
      IconData(0xe830, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowDown2 =
      IconData(0xe831, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowDown3 =
      IconData(0xe832, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowDownCircle =
      IconData(0xe833, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowDownSquare =
      IconData(0xe834, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowDown =
      IconData(0xe835, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowLeft2 =
      IconData(0xe836, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowLeft3 =
      IconData(0xe837, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowLeftCircle =
      IconData(0xe838, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowLeftSquare =
      IconData(0xe839, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowLeft =
      IconData(0xe83a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowRight2 =
      IconData(0xe83b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowRight3 =
      IconData(0xe83c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowRightCircle =
      IconData(0xe83d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowRightSquare =
      IconData(0xe83e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowRight =
      IconData(0xe83f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowUp3 =
      IconData(0xe840, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowUp2 =
      IconData(0xe841, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowUpCircle =
      IconData(0xe842, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowUpSquare =
      IconData(0xe843, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowUp =
      IconData(0xe844, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData buy =
      IconData(0xe845, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData camera =
      IconData(0xe846, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData closeSquare =
      IconData(0xe847, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData danger =
      IconData(0xe848, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData delete =
      IconData(0xe849, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData discount =
      IconData(0xe84a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData editSquare =
      IconData(0xe84b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData edit =
      IconData(0xe84c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData folder =
      IconData(0xe84d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData infoCircle =
      IconData(0xe84e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData infoSquare =
      IconData(0xe84f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData moreSquare =
      IconData(0xe850, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData moreCircle =
      IconData(0xe851, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paperDownload =
      IconData(0xe852, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paperFail =
      IconData(0xe853, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paperNegative =
      IconData(0xe854, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paperUpload =
      IconData(0xe855, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paperPlus =
      IconData(0xe856, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData play =
      IconData(0xe857, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paper =
      IconData(0xe858, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData search =
      IconData(0xe859, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData setting =
      IconData(0xe85a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shieldDone =
      IconData(0xe85b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData tickSquare =
      IconData(0xe85c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData timeCircle =
      IconData(0xe85d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData timeSquare =
      IconData(0xe85e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData voice2 =
      IconData(0xe85f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData volumeDown =
      IconData(0xe860, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData voice =
      IconData(0xe861, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData volumeOff =
      IconData(0xe862, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData volumeUp =
      IconData(0xe863, fontFamily: kFontFam, fontPackage: kFontPkg);
}
